### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by mjobin** [kveeramah/GenoCaller_indent#1]
We're excited to try GenoCaller, but we are getting an error on running right after install:
  File "GenoCaller_indent.py", line 284
    outB='##INFO=<ID=AC,Number=A,Type=Integer,Description="Allele count in genotypes, for each ALT allele, in the same order as listed">\n'
       ^
SyntaxError: invalid syntax

It looks maybe like there is an extra newline in the source code, but not sure. We've tried it out in python 2.7 and 3.

**Comment by kveeramah** [comment]
Sorry, there was a very silly error with a non-closed parenthesis on the line above. It should be fixed now. Let me know if there are other issues.

Cheers
Krishna

**Comment by mjobin** [comment]
It's working great now. Thank you!
